version: 2.1

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: cimg/node:20.8 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

