version: 2.1

workflow:
  version: 2
  build:
    job:
      - bulid:
        filters:
          branches:
            olny:
              - main

job:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependancy-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependancy-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules