version: 2.1

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: cimg/node:10.16.3
    steps:
      - checkout
      - run:
          name: Set up npm global path
          command: |
            mkdir -p $HOME/.npm-global
            echo 'export PATH=$HOME/.npm-global/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update npm
          command: npm install -g npm@latest --prefix=$HOME/.npm-global
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
